CREATE TABLE Sheet1(------------------------------------------_Basic_Queries_------------------------- VARCHAR(10));
INSERT INTO Sheet1 (------------------------------------------_Basic_Queries_-------------------------) VALUES 
('select * from ads'),
('select * from campaigns'),
('select * from users'),
('select * from ad_events'),
('/*'),
('  A Comprehensive Study Of KPIs'),
('*/'),
('------------------------------------------  Impressions  -------------------------'),
('SELECT'),
('    ads.ad_platform as Platforms,'),
('    COUNT(add_event.event_type) AS Impression_count'),
('FROM'),
('    ad_events '),
('INNER JOIN'),
('    ads '),
('ON'),
('    ad_event.ad_id = ads.ad_id'),
('WHERE'),
('    ad_event.event_type = 'Impression''),
('GROUP BY'),
('    ads.ad_platform'),
('    ------------------------------------------   Clicks  -------------------------'),
('SELECT'),
('    adds.ad_platform as Platforms,'),
('    COUNT(ad_event.event_type) AS Click_count'),
('FROM'),
('    ad_events '),
('INNER JOIN'),
('    ads '),
('ON'),
('    ad_event.ad_id = ads.ad_id'),
('WHERE'),
('    ad_event.event_type = 'Click''),
('GROUP BY'),
('    ads.ad_platform'),
('        ------------------------------------------   Shares  -------------------------'),
('SELECT'),
('    ads.ad_platform as Platforms,'),
('    COUNT(ad_event.event_type) AS Share_count'),
('FROM'),
('    ad_events '),
('INNER JOIN'),
('    ads '),
('ON'),
('    ad_event.ad_id = ads.ad_id'),
('WHERE'),
('    ad_event.event_type = 'Share''),
('GROUP BY'),
('    ads.ad_platform'),
('     ------------------------------------------   Comments  -------------------------'),
('SELECT'),
('    ads.ad_platform as Platforms,'),
('    COUNT(ad_event.event_type) AS Comment_count'),
('FROM'),
('    ad_events'),
('INNER JOIN'),
('    ads '),
('ON'),
('    ad_event.ad_id = ads.ad_id'),
('WHERE'),
('    ad_event.event_type = 'Comment''),
('GROUP BY'),
('    ads.ad_platform'),
('     ------------------------------------------    Purchases  -------------------------'),
('SELECT'),
('    ads.ad_platform as Platforms,'),
('    COUNT(ad_event.event_type) AS Purchase_count'),
('FROM'),
('    ad_events '),
('INNER JOIN'),
('    ads ON'),
('    ad_event.ad_id = ads.ad_id'),
('WHERE'),
('    ad_event.event_type = 'Purchase''),
('GROUP BY'),
('    ads.ad_platform'),
('     ------------------------------------------   CTR (Click Through Rate)  -------------------------'),
('     -- (Clicks ÷ Impressions) × 100'),
('SELECT '),
('    ads.ad_platform,'),
('     SUM(CASE WHEN ad_event.event_type = 'impression' THEN 1 ELSE 0 END) AS impressions,'),
('    SUM(CASE WHEN ad_event.event_type = 'click' THEN 1 ELSE 0 END) AS clicks,'),
('    ROUND('),
('         (SUM(CASE WHEN ad_event.event_type = 'click' THEN 1 ELSE 0 END)   '),
('            * 100 /'),
('            NULLIF'),
('            (SUM(CASE WHEN ad_event.event_type = 'impression' THEN 1 ELSE 0 END), 0)'),
('         ),'),
('        2'),
('    ) AS ctr_percentage'),
('FROM ad_events '),
('JOIN ads '),
('    ON ad_event.ad_id = ads.ad_id'),
('GROUP BY ads.ad_platform;'),
(' ------------------------------------------    Engagement Rate  -------------------------'),
(' ---(Engagements ÷ Impressions) × 100 '),
(' ---(Engagement = Clicks + Shares + Comments)'),
('SELECT '),
('    ads.ad_platform,'),
('    SUM(CASE WHEN ad_event.event_type = 'impression' THEN 1 ELSE 0 END) AS impressions,'),
('    SUM(CASE WHEN ad_event.event_type In ('click','Share','Comment') THEN 1 ELSE 0 END) AS Engagement,'),
('    ROUND('),
('         (SUM(CASE WHEN ad_event.event_type In ('click','Share','Comment') THEN 1 ELSE 0 END)   '),
('            * 100.0 /'),
('            NULLIF'),
('            (SUM(CASE WHEN ad_event.event_type = 'impression' THEN 1 ELSE 0 END), 0)'),
('         ),'),
('        2'),
('    ) AS Eng_percentage'),
('FROM ad_events '),
('JOIN ads '),
('    ON ad_event.ad_id = ads.ad_id'),
('GROUP BY ads.ad_platform;'),
('------------------------------------------    Conversion Rate  -------------------------'),
(' ---(Purchases ÷ Clicks) × 100'),
(' '),
('SELECT '),
('    ads.ad_platform,'),
('    SUM(CASE WHEN ad_event.event_type = 'Purchase' THEN 1 ELSE 0 END) AS Purchase,'),
('    ROUND('),
('         (SUM(CASE WHEN ad_event.event_type = 'Purchase' THEN 1 ELSE 0 END)   '),
('            * 100.0 /'),
('            NULLIF'),
('            (SUM(CASE WHEN ad_event.event_type = 'Click' THEN 1 ELSE 0 END), 0)'),
('         ),'),
('        2'),
('    ) AS Conversion_percentage'),
('FROM ad_events '),
('JOIN ads'),
('    ON ad_event.ad_id = ads.ad_id'),
('GROUP BY ads.ad_platform;'),
('------------------------------------------    Purchase Rate  -------------------------'),
(' --- (Purchases ÷ Impressions) × 100'),
(' '),
('SELECT '),
('    ads.ad_platform,'),
('    SUM(CASE WHEN ad_event.event_type = 'Purchase' THEN 1 ELSE 0 END) AS Purchase,'),
('    ROUND('),
('         (SUM(CASE WHEN ad_event.event_type = 'Purchase' THEN 1 ELSE 0 END)   '),
('            * 100.0 /'),
('            NULLIF'),
('            (SUM(CASE WHEN ad_event.event_type = 'Impression' THEN 1 ELSE 0 END), 0)'),
('         ),'),
('        2'),
('    ) AS Purchase_Rate'),
('FROM ad_events '),
('JOIN ads '),
('    ON ad_event.ad_id = ads.ad_id'),
('GROUP BY ads.ad_platform;'),
('------------------------------------------   Total Budget  -------------------------'),
('select sum(total_budget) as TotalBudget from campaigns'),
('select count(total_budget) as TotalBudget from campaigns');